set(CPACK_PACKAGE_NAME ${CMAKE_PROJECT_NAME})
set(CPACK_PACKAGE_VENDOR ${PROJECT_VENDOR})
set(CPACK_PACKAGE_CONTACT ${PROJECT_CONTACT})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY ${PROJECT_DESCRIPTION})

set(CPACK_PACKAGE_VERSION ${DEMO_VERSION_STRING})
set(CPACK_PACKAGE_VERSION_MAJOR ${DEMO_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${DEMO_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${DEMO_VERSION_PATCH})

set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_RPM_PACKAGE_GROUP ${PROJECT_PACKAGE_GROUP})
set(CPACK_RPM_PACKAGE_URL ${PROJECT_URL})
set(CPACK_RPM_PACKAGE_DESCRIPTION ${PROJECT_DESCRIPTION_LONG})
set(CPACK_RPM_PACKAGE_LICENSE ${PROJECT_LICENSE})
set(CPACK_RPM_SPEC_MORE_DEFINE "%define _build_id_links none")
set(CPACK_RPM_COMPRESSION_TYPE "lzma")

set(CPACK_PACKAGE_RELEASE 1)
set(CPACK_PACKAGE_CHECKSUM "MD5")

set(CPACK_PACKAGE_FILE_NAME ${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}_${DEMO_BUILD_NUMBER}-${CPACK_PACKAGE_RELEASE}.${CMAKE_SYSTEM_PROCESSOR})
set(CPACK_SOURCE_PACKAGE_FILE_NAME ${CPACK_PACKAGE_NAME}-${DEMO_VERSION_STRING})

set(CPACK_GENERATOR RPM)
set(CPACK_SOURCE_GENERATOR "TGZ")

set(CPACK_SOURCE_IGNORE_FILES "/\\\\.gitattributes;/\\\\.vagrant;/\\\\.DS_Store;/CVS/;/\\\\.git/;\\\\.swp$;~$;\\\\.\\\\#;/\\\\#")
list(APPEND CPACK_SOURCE_IGNORE_FILES "/\\\\.clion.source.upload.marker")
list(APPEND CPACK_SOURCE_IGNORE_FILES "${CMAKE_CURRENT_BINARY_DIR}")

include(CPack)
